version: '3'
services:
  database:
    image: rethinkdb:latest
    ports:
      - '28015'
      - '29015'
      - '8080'

  fastapi:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - '80:80'
